x-defaults: &defaults
  environment:
    - SD_WEBUI_CONFIG_PATH=/sdcpp-webui/config.json
    - SD_WEBUI_PROMPTS_PATH=/sdcpp-webui/prompts.json
  ports:
    - "7860:7860"
  user: "1000"
  group_add:
    - video # 44
    - 132 # render
  volumes:
    - ./docker/.cache/:/.cache:rw
    - ./docker/config.json:/sdcpp-webui/config.json:rw
    - ./docker/prompts.json:/sdcpp-webui/prompts.json:rw
    - ./docker/options_cache.json:/usr/local/src/options_cache.json:rw
    - ./outputs:/usr/local/src/outputs:rw
    - /mnt/tank/models:/usr/local/models:rw
  devices:
    - /dev/dri/renderD129:/dev/dri/renderD129
    - /dev/kfd:/dev/kfd
  shm_size: '8G'
  ipc: 'host'
  security_opt:
    - seccomp:unconfined
  ulimits:
    core:
      hard: 0
      soft: 0


services:
  web-rocm:
    <<: *defaults
    build:
      context: .
      dockerfile: ./docker/Dockerfile.rocm
      args:
        ROCM_VERSION: "7.1.1"
        SDCPP_VERSION: "rocm7.1-gfx1030"
    image: sdcpp-webui:rocm7.1-gfx1030
    ports:
      - "7861:7860"
    environment:
      - HSA_OVERRIDE_GFX_VERSION=10.3.0 # rocm for rdna2
      - LD_LIBRARY_PATH=/opt/rocm/lib/llvm/lib
      - SD_WEBUI_CONFIG_PATH=/sdcpp-webui/config.json
      - SD_WEBUI_PROMPTS_PATH=/sdcpp-webui/prompts.json

  web-vulkan:
    <<: *defaults
    build:
      context: .
      dockerfile: ./docker/Dockerfile.vulkan
      args:
        SDCPP_VERSION: "master-vulkan"
    image: sdcpp-webui:vulkan
